site_name: Rago Hub
site_url: https://ragohub.github.io

theme:
  name: material
  palette:
  - scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

plugins:
  - search
  - macros

extra_css:
  - stylesheets/extra.css
  - stylesheets/discordEmbed.css
  - stylesheets/discordInvite.css
